Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,11 +25,24 @@ jobs:
             # JMeter test plan to execute
           test-plan-path: './orangeHRMdemo.jmx'
 
+      - name: Debug directory
+        run: find . -type f
+
       - name: Upload Results
         uses: actions/upload-artifact@v3
         with:
           name: jmeter-results
-          path: ./result.jtl
+          path: result.jtl
+          if-no-files-found: error
+
+      - name: Debug reports directory
+        run: ls -la reports || echo "Reports directory not found"
+
+      - name: Upload HTML Reports
+        uses: actions/upload-artifact@v3
+        with:
+          name: jmeter-html-reports
+          path: reports
           if-no-files-found: error
 
    
